# -*- coding: utf-8 -*-
"""Untitled73.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Pp9NOeXQu7pXLja_KSsLWUVFlbizMkcf
"""

pip install pandas

import pandas as pd
import numpy as np

# [cite_start]'courses_data (2).csv' faylini yuklash [cite: 1]
df = pd.read_csv('courses_data (2).csv')

# Keraksiz ustunlarni olib tashlash (agar kerak bo'lsa, qisqartirish uchun)
df = df[['교과목명', '수강인원', '강좌담당교수', '수업주수', '교과목학점', '강의유형구분']]

print("Yuklangan ma'lumotlar (dastlabki 5 qator):")
print(df.head())
print("\nFanlarning umumiy soni:", len(df))

# Auditoriyalar va ularning maksimal sig'imi
AUDITORIYALAR = {
    '1215': 40,  # Asosiy (Ustuvor)
    '1216': 40,  # Asosiy (Ustuvor)
    '1217': 35,  # Asosiy (Ustuvor)
    '1418': 35,  # Asosiy (Ustuvor)
    '9999 (Ijara)': 45 # Ijaraga olingan (Eng oxirgi foydalaniladi)
}
ASOSIY_AUDITORIYALAR = ['1215', '1216', '1217', '1418']

# Dushanba-Juma
KUNLAR = ['Dushanba', 'Seshanba', 'Chorshanba', 'Payshanba', 'Juma']

# Har bir kunda 3 ta vaqt bloki (masalan: 9:00-11:45, 12:00-14:45, 15:00-17:45)
VAQT_BLOKLARI = ['V_Blok_1', 'V_Blok_2', 'V_Blok_3']

# Jadvalni initsializatsiya qilish (Auditoriya, Kun, Vaqt)
# Bu lug'at keyinchalik band qilingan vaqt bloklarini saqlaydi.
jadval_holati = {room: {day: {slot: None for slot in VAQT_BLOKLARI} for day in KUNLAR} for room in AUDITORIYALAR}

# Professorning bandlik holatini tekshirish uchun lug'at
professor_bandligi = {day: {slot: None for slot in VAQT_BLOKLARI} for day in KUNLAR}

# Talaba soni (수강인원) bo'yicha kamayish tartibida saralash
darslar_saralangan = df.sort_values(by='수강인원', ascending=False)

# Yakuniy dars jadvali natijasini saqlash uchun ro'yxat
yakuniy_jadval_natija = []

for index, dars in darslar_saralangan.iterrows():
    fan_nomi = dars['교과목명']
    talaba_soni = dars['수강인원']
    professor = dars['강좌담당교수']
    haftalik_soat = dars['교과목학점'] # 3 kredit = 3 soat deb taxmin qilinadi

    # Dars qaysi kun va vaqtda o'tilishini aniqlash.
    # Har bir dars uchun (haftalik_soat) marta ta'minot qilish kerak (agar bu 1 soatlik bloklar bo'lsa).
    # Ammo, soddalik uchun, har bir dars o'zining "haftalik_soati" bo'yicha 1 ta to'liq blokni egallaydi, deb faraz qilamiz.

    # Har bir fan uchun bir hafta davomida qancha blok kerak (hozircha 1 ta blok deb soddalashtiramiz,
    # chunki bitta qatorda bir dars bor. Agar 3 soat kerak bo'lsa, bu yerda 3 marta ta'minot kerak)

    # Ta'minot uchun mos joy topilguncha davom etish
    joylashdi = False

    # 1. Auditoriya ustuvorligiga rioya qilish (1215, 1216, 1217, 1418, keyin 9999)
    # Auditoriyalar lug'atini ro'yxatga aylantirish, ustuvorlik tartibida saralash
    sorted_rooms = list(AUDITORIYALAR.keys())

    for room_id in sorted_rooms:
        room_sigimi = AUDITORIYALAR[room_id]

        # Qattiq Cheklov 1: Sig'im cheklovi
        if talaba_soni > room_sigimi:
            continue # Bu auditoriya juda kichik

        # Auditoriyaning bo'sh vaqtini qidirish
        for day in KUNLAR:
            for slot in VAQT_BLOKLARI:

                # Qattiq Cheklov 2 & 3: Vaqt bloki va Professor bandligi cheklovi
                if jadval_holati[room_id][day][slot] is None and professor_bandligi[day][slot] != professor:

                    # Joylashdi!
                    jadval_holati[room_id][day][slot] = fan_nomi # Auditoriyani band qilish
                    professor_bandligi[day][slot] = professor     # Professorlikni band qilish

                    yakuniy_jadval_natija.append({
                        'Fan': fan_nomi,
                        'Talaba soni': talaba_soni,
                        'Professor': professor,
                        'Auditoriya': room_id,
                        'Kun': day,
                        'Vaqt Bloki': slot,
                        'Sig\'im Farqi': room_sigimi - talaba_soni
                    })

                    joylashdi = True
                    break # Vaqt blokidan chiqish
            if joylashdi:
                break # Kunda chiqish
        if joylashdi:
            break # Auditoriyadan chiqish

    if not joylashdi:
        print(f"⚠️ {fan_nomi} ({talaba_soni} talaba) uchun mos joy topilmadi. Jadval to'liq.")

final_df = pd.DataFrame(yakuniy_jadval_natija)

# Natijani Auditoriya va Kun bo'yicha tartiblash
final_df_sorted = final_df.sort_values(by=['Auditoriya', 'Kun', 'Vaqt Bloki'])

print("\n✅ Yakuniy Dars Jadvali Natijasi:")
print(final_df_sorted)

# Optimallashtirish Tahlili
ijara_foydalanishi = final_df[final_df['Auditoriya'] == '9999 (Ijara)'].shape[0]
umumiy_darslar = final_df.shape[0]

print("\n--- Optimallashtirish Hisoboti ---")
print(f"Umumiy ta'minlangan darslar: {umumiy_darslar} ta")
print(f"9999 (Ijara) auditoriyasidan foydalanish: {ijara_foydalanishi} marta (Buni minimallashtirish kerak)")

# Yakuniy dars jadvali natijasini saqlash uchun ro'yxat
yakuniy_jadval_natija = []
darslar_saralangan = df.sort_values(by='수강인원', ascending=False)

print("Optimallashtirilgan taqsimot boshlandi...")

for index, dars in darslar_saralangan.iterrows():
    fan_nomi = dars['교과목명']
    talaba_soni = dars['수강인원']
    professor = dars['강좌담당교수']

    eng_yaxshi_tanlov = None
    eng_kam_jarima = float('inf') # Cheksiz yuqori ball

    # 1. Barcha mumkin bo'lgan bo'sh joylarni qidirish va jarimani hisoblash

    # Auditoriyalar ustuvorlik tartibida bo'lishi shart emas, chunki jarima balli bu ustuvorlikni o'z ichiga oladi.
    for room_id, room_sigimi in AUDITORIYALAR.items():

        # Qattiq Cheklov 1: Sig'im cheklovi
        if talaba_soni > room_sigimi:
            continue

        for day in KUNLAR:
            for slot in VAQT_BLOKLARI:

                # Qattiq Cheklov 2 & 3: Vaqt bloki va Professor bandligi cheklovi
                if jadval_holati[room_id][day][slot] is None and professor_bandligi[day][slot] != professor:

                    # --- Yumshoq Cheklovlar va Jarima Hisobi ---
                    jarima = 0
                    sigim_farqi = room_sigimi - talaba_soni

                    # 1-Muzokaralar (Ijara Auditoriyasi Jarimasi)
                    if room_id == '9999 (Ijara)':
                        jarima += 100 # Katta jarima balli

                    # 2-Muzokaralar (Sig'im Farqi Jarimasi - Bo'sh joyni kamaytirish)
                    # Sig'im farqi qancha katta bo'lsa, jarima shuncha yuqori
                    jarima += sigim_farqi * 1 # Masalan, har bir bo'sh joy uchun 1 ball

                    # Eng yaxshi joyni tanlash
                    if jarima < eng_kam_jarima:
                        eng_kam_jarima = jarima
                        eng_yaxshi_tanlov = {
                            'Auditoriya': room_id,
                            'Kun': day,
                            'Vaqt Bloki': slot,
                            'Sig\'im Farqi': sigim_farqi
                        }

    # 2. Eng yaxshi topilgan joyga darsni joylashtirish
    if eng_yaxshi_tanlov:
        room_id = eng_yaxshi_tanlov['Auditoriya']
        day = eng_yaxshi_tanlov['Kun']
        slot = eng_yaxshi_tanlov['Vaqt Bloki']

        # Jadvalni yangilash
        jadval_holati[room_id][day][slot] = fan_nomi
        professor_bandligi[day][slot] = professor

        yakuniy_jadval_natija.append({
            'Fan': fan_nomi,
            'Talaba soni': talaba_soni,
            'Professor': professor,
            **eng_yaxshi_tanlov
        })

    else:
        print(f"⚠️ {fan_nomi} ({talaba_soni} talaba) uchun mos joy topilmadi (barcha cheklovlar buziladi).")

print("Optimallashtirilgan taqsimot yakunlandi.")
# Auditoriyalar va ularning maksimal sig'imi
AUDITORIYALAR = {
    '1215': 40,
    '1216': 40,
    '1217': 35,
    '1418': 35,
    '9999 (Ijara)': 45
}
ASOSIY_AUDITORIYALAR = ['1215', '1216', '1217', '1418']

# Dushanba-Juma
KUNLAR = ['Dushanba', 'Seshanba', 'Chorshanba', 'Payshanba', 'Juma']

# Har bir kunda 3 ta vaqt bloki
VAQT_BLOKLARI = ['V_Blok_1', 'V_Blok_2', 'V_Blok_3']

# Jadvalni initsializatsiya qilish (Auditoriya, Kun, Vaqt)
# BU YERDA TOZALASH SODIR BO'LADI!
jadval_holati = {room: {day: {slot: None for slot in VAQT_BLOKLARI} for day in KUNLAR} for room in AUDITORIYALAR}

# Professorning bandlik holatini tekshirish uchun lug'at
professor_bandligi = {day: {slot: None for slot in VAQT_BLOKLARI} for day in KUNLAR}

# --- Qadam 4 Kod Blokini Ishga Tushirish ---

final_df = pd.DataFrame(yakuniy_jadval_natija)

# Natijani Auditoriya va Kun bo'yicha tartiblash
final_df_sorted = final_df.sort_values(by=['Auditoriya', 'Kun', 'Vaqt Bloki'])

print("\n✅ Yakuniy Dars Jadvali Natijasi:")
print(final_df_sorted)

# Optimallashtirish Tahlili
ijara_foydalanishi = final_df[final_df['Auditoriya'] == '9999 (Ijara)'].shape[0]
umumiy_darslar = final_df.shape[0]

print("\n--- Optimallashtirish Hisoboti ---")
print(f"Umumiy ta'minlangan darslar: {umumiy_darslar} ta")
print(f"9999 (Ijara) auditoriyasidan foydalanish: {ijara_foydalanishi} marta (Buni minimallashtirish kerak)")